# github: ["ProdigyPNP"] # GitHub Sponsors
patreon: "ProdigyHacking" # Patreon
open_collective: "ProdigyPNP" # Open Collective
custom: ["https://paypal.me/ProdigyDMCA", "https://dsc.gg/ProdigyPNP"] # PayPal, Discord
